services:
  app:
    build:
        context: .
        dockerfile: docker/php/Dockerfile
    container_name: laravel_api
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - mysql
      - redis
    networks:
      - laravel
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  redis:
    image: redis:7.2.4
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command:
        redis-server --requirepass SUA_SENHA
    networks:
        - laravel


volumes:
  dbdata:
  redis-data:

networks:
  laravel:
    driver: bridge
